export const Orders = [
    {
      id: "#CM9801",
      user: { name: "Natali Craig", avatar: "/assets/contacts/andi.png" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
      statusColor: "bg-blue-400",
    },
    {
      id: "#CM9802",
      user: { name: "Kate Morrison", avatar: "/assets/contacts/drew.png" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
      statusColor: "bg-green-400",
    },
    {
      id: "#CM9803",
      user: { name: "Drew Cano", avatar: "/assets/contacts/kate.png" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
      statusColor: "bg-sky-400",
    },
    {
      id: "#CM9804",
      user: { name: "Orlando Diggs", avatar: "/assets/contacts/koray.png" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
      statusColor: "bg-yellow-400",
    },
    {
      id: "#CM9805",
      user: { name: "Andi Lane", avatar: "/assets/contacts/natali.png" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
      statusColor: "bg-gray-400",
    },
    {
      id: "#CM9806",
      user: { name: "Kate Morrison", avatar: "/assets/contacts/drew.png" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
      statusColor: "bg-green-400",
    },
    {
      id: "#CM9807",
      user: { name: "Drew Cano", avatar: "/assets/contacts/kate.png" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
      statusColor: "bg-sky-400",
    },
    {
      id: "#CM9808",
      user: { name: "Natali Craig", avatar: "/assets/contacts/andi.png" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
      statusColor: "bg-blue-400",
    },
    {
      id: "#CM9809",
      user: { name: "Kate Morrison", avatar: "/assets/contacts/drew.png" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
      statusColor: "bg-green-400",
    },
    {
      id: "#CM9810",
      user: { name: "Natali Craig", avatar: "/assets/contacts/andi.png" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
      statusColor: "bg-blue-400",
    },
    {
      id: "#CM9811",
      user: { name: "Kate Morrison", avatar: "/assets/contacts/drew.png" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
      statusColor: "bg-green-400",
    },
    {
      id: "#CM9812",
      user: { name: "Drew Cano", avatar: "/assets/contacts/kate.png" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
      statusColor: "bg-sky-400",
    },
    {
      id: "#CM9813",
      user: { name: "Orlando Diggs", avatar: "/assets/contacts/koray.png" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
      statusColor: "bg-yellow-400",
    },
  ];
